language: node_js
node_js:
  - 13

services:
  - docker

#pre-testing installs
install:
  - echo  "nothing needs to be installed"

# Scripts to run as tests
before_script:
- echo "no test"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed celiaxz/udagram-api-feed:v1
  - docker tag udagram-api-user celiaxz/udagram-api-user:v1
  - docker tag udagram-frontend celiaxz/udagram-frontend:v1
  - docker tag udagram-reverseproxy celiaxz/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "DOKER_USERNAME" --password-stdin
  - docker push celiaxz/udagram-api-feed:v1
  - docker push celiaxz/udagram-api-user:v1
  - docker push celiaxz/udagram-frontend:v1
  - docker push celiaxz/udagram-reverseproxy:v1